language: python

python:
  - 2.7

addons:
  postgresql: "9.5"

before_install:
  - psql -c 'create database catalex_sign_test;' -U postgres

install: python setup.py
script: CONFIG_FILE=config_test.py python -m unittest discover